apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ucg9k9t9z-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ucg9k9t9z-python 
  name: ucg9k9t9z-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ucg9k9t9z-python 
