apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ucg9k9t9z-python 
  janus-idp.io/tekton: ucg9k9t9z-python
  backstage.io/kubernetes-id: ucg9k9t9z-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ucg9k9t9z-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml